services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=0000
            - MYSQL_DB=library
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_ALLOW_EMPTY_PASSWORD=false
            - MYSQL_RANDOM_ROOT_PASSWORD=false
        ports:
            - 5431:5432
        networks:
            - mysql

    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./app/main
        ports:
            - 8080:8080
        networks:
            - mysql
        volumes:
            - go-modules:/go/pkg/mod
        depends_on:
            - mysql
networks:
    mysql:
        driver: bridge

volumes:
    go-modules:
