// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/service/grpc/pb/library.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookRequest) Reset()         { *m = BookRequest{} }
func (m *BookRequest) String() string { return proto.CompactTextString(m) }
func (*BookRequest) ProtoMessage()    {}
func (*BookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b3c66e1403fcf3, []int{0}
}

func (m *BookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookRequest.Unmarshal(m, b)
}
func (m *BookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookRequest.Marshal(b, m, deterministic)
}
func (m *BookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookRequest.Merge(m, src)
}
func (m *BookRequest) XXX_Size() int {
	return xxx_messageInfo_BookRequest.Size(m)
}
func (m *BookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookRequest proto.InternalMessageInfo

func (m *BookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AuthorRequest struct {
	LastName             string   `protobuf:"bytes,1,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorRequest) Reset()         { *m = AuthorRequest{} }
func (m *AuthorRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorRequest) ProtoMessage()    {}
func (*AuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b3c66e1403fcf3, []int{1}
}

func (m *AuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorRequest.Unmarshal(m, b)
}
func (m *AuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorRequest.Marshal(b, m, deterministic)
}
func (m *AuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorRequest.Merge(m, src)
}
func (m *AuthorRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorRequest.Size(m)
}
func (m *AuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorRequest proto.InternalMessageInfo

func (m *AuthorRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type BookResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookResponse) Reset()         { *m = BookResponse{} }
func (m *BookResponse) String() string { return proto.CompactTextString(m) }
func (*BookResponse) ProtoMessage()    {}
func (*BookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b3c66e1403fcf3, []int{2}
}

func (m *BookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookResponse.Unmarshal(m, b)
}
func (m *BookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookResponse.Marshal(b, m, deterministic)
}
func (m *BookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookResponse.Merge(m, src)
}
func (m *BookResponse) XXX_Size() int {
	return xxx_messageInfo_BookResponse.Size(m)
}
func (m *BookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookResponse proto.InternalMessageInfo

func (m *BookResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AuthorResponse struct {
	LastName             string   `protobuf:"bytes,1,opt,name=lastName,proto3" json:"lastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorResponse) Reset()         { *m = AuthorResponse{} }
func (m *AuthorResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorResponse) ProtoMessage()    {}
func (*AuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1b3c66e1403fcf3, []int{3}
}

func (m *AuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorResponse.Unmarshal(m, b)
}
func (m *AuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorResponse.Marshal(b, m, deterministic)
}
func (m *AuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorResponse.Merge(m, src)
}
func (m *AuthorResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorResponse.Size(m)
}
func (m *AuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorResponse proto.InternalMessageInfo

func (m *AuthorResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*BookRequest)(nil), "library.BookRequest")
	proto.RegisterType((*AuthorRequest)(nil), "library.AuthorRequest")
	proto.RegisterType((*BookResponse)(nil), "library.BookResponse")
	proto.RegisterType((*AuthorResponse)(nil), "library.AuthorResponse")
}

func init() {
	proto.RegisterFile("internal/service/grpc/pb/library.proto", fileDescriptor_c1b3c66e1403fcf3)
}

var fileDescriptor_c1b3c66e1403fcf3 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x4f, 0x2f, 0x2a,
	0x48, 0xd6, 0x2f, 0x48, 0xd2, 0xcf, 0xc9, 0x4c, 0x2a, 0x4a, 0x2c, 0xaa, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x94, 0xb9, 0xb8, 0x9d, 0xf2, 0xf3, 0xb3, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x6d, 0x2e, 0x5e, 0xc7, 0xd2, 0x92, 0x8c, 0xfc,
	0x22, 0x98, 0x32, 0x29, 0x2e, 0x8e, 0x9c, 0xc4, 0xe2, 0x12, 0xbf, 0xc4, 0x5c, 0x98, 0x4a, 0x38,
	0x5f, 0x49, 0x85, 0x8b, 0x07, 0x62, 0x62, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x0e, 0x23, 0x75,
	0xb8, 0xf8, 0x60, 0x46, 0x42, 0xd5, 0xe1, 0x31, 0xd3, 0xa8, 0x95, 0x91, 0x8b, 0xdd, 0x07, 0xe2,
	0x62, 0x21, 0x6b, 0x2e, 0x0e, 0xb7, 0xcc, 0xbc, 0x14, 0x90, 0x1d, 0x42, 0x62, 0x7a, 0x30, 0x6f,
	0xa1, 0xb8, 0x4f, 0x4a, 0x14, 0x2e, 0x8e, 0xec, 0x14, 0x25, 0x06, 0x21, 0x5b, 0x2e, 0x2e, 0x90,
	0x66, 0x88, 0x6a, 0x21, 0x11, 0x34, 0x65, 0x10, 0xcd, 0xe2, 0x18, 0x86, 0xc2, 0xb4, 0x3b, 0x49,
	0x45, 0x49, 0xe0, 0x0a, 0xe0, 0x24, 0x36, 0x70, 0xc8, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xeb, 0xdc, 0xb8, 0x86, 0x83, 0x01, 0x00, 0x00,
}
